<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Sample.OverEngineered.Authorization/Sample.OverEngineered.Authorization.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Cache/Sample.OverEngineered.Cache.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Domain/Sample.OverEngineered.Domain.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Infrastructure/Sample.OverEngineered.Infrastructure.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Messaging/Sample.OverEngineered.Messaging.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Persistence/Sample.OverEngineered.Persistence.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.ReadModel/Sample.OverEngineered.ReadModel.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Telemetry/Sample.OverEngineered.Telemetry.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.Validation/Sample.OverEngineered.Validation.csproj" />
    <ProjectReference Include="../Sample.OverEngineered.WriteModel/Sample.OverEngineered.WriteModel.csproj" />
  </ItemGroup>
</Project>
