using System.Collections.Concurrent;

namespace SimplicityTools.Metrics;

internal static class SourceFileConventions
{
    // Memoizes the on-disk auto-generated-marker probe per file path. The cache is never
    // invalidated: a collection run is a short-lived process, and every pass asks about the
    // same files many times, so trading staleness (a file whose first 20 lines change while
    // the process runs) for not re-reading thousands of files from disk is the right call.
    private static readonly ConcurrentDictionary<string, bool> AutoGeneratedMarkerCache =
        new(StringComparer.OrdinalIgnoreCase);

    public static bool IsCountableSourceFile(string path)
    {
        if (string.IsNullOrWhiteSpace(path) ||
            !string.Equals(Path.GetExtension(path), ".cs", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (path.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (ContainsDirectorySegment(path, "bin") || ContainsDirectorySegment(path, "obj"))
        {
            return false;
        }

        return !ContainsAutoGeneratedMarker(path);
    }

    public static bool IsTestProject(string? projectPath, string projectName)
    {
        if (projectName.EndsWith(".Tests", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return !string.IsNullOrWhiteSpace(projectPath) &&
               !ContainsDirectorySegment(projectPath, "TestData") &&
               ContainsDirectorySegment(projectPath, "tests");
    }

    public static bool ContainsDirectorySegment(string path, string segment)
    {
        var normalizedPath = path.Replace('\\', '/');
        return normalizedPath.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Any(part => string.Equals(part, segment, StringComparison.OrdinalIgnoreCase));
    }

    private static bool ContainsAutoGeneratedMarker(string path)
    {
        return AutoGeneratedMarkerCache.GetOrAdd(path, static candidate => ReadAutoGeneratedMarker(candidate));
    }

    private static bool ReadAutoGeneratedMarker(string path)
    {
        if (!File.Exists(path))
        {
            return false;
        }

        foreach (var line in File.ReadLines(path).Take(20))
        {
            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
