namespace SimplicityTools.Metrics;

internal static class SourceFileConventions
{
    public static bool IsCountableSourceFile(string path)
    {
        if (string.IsNullOrWhiteSpace(path) ||
            !string.Equals(Path.GetExtension(path), ".cs", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (path.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (ContainsDirectorySegment(path, "bin") || ContainsDirectorySegment(path, "obj"))
        {
            return false;
        }

        return !ContainsAutoGeneratedMarker(path);
    }

    public static bool IsTestProject(string? projectPath, string projectName)
    {
        if (projectName.EndsWith(".Tests", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return !string.IsNullOrWhiteSpace(projectPath) &&
               !ContainsDirectorySegment(projectPath, "TestData") &&
               ContainsDirectorySegment(projectPath, "tests");
    }

    public static bool ContainsDirectorySegment(string path, string segment)
    {
        var normalizedPath = path.Replace('\\', '/');
        return normalizedPath.Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Any(part => string.Equals(part, segment, StringComparison.OrdinalIgnoreCase));
    }

    private static bool ContainsAutoGeneratedMarker(string path)
    {
        if (!File.Exists(path))
        {
            return false;
        }

        foreach (var line in File.ReadLines(path).Take(20))
        {
            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
