using Xunit;

namespace SimplicityTools.Metrics.Tests;

public sealed class SourceFileConventionsTests
{
    [Fact]
    public void IsCountableSourceFile_MemoizesAutoGeneratedMarker_PerFilePath()
    {
        var path = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.cs");
        File.WriteAllText(path, "// <auto-generated />\nnamespace Cached;\n");

        try
        {
            Assert.False(SourceFileConventions.IsCountableSourceFile(path));

            // Deleting the file makes an uncached read report "no marker" (and therefore
            // countable); the memoized result must survive the deletion.
            File.Delete(path);

            Assert.False(SourceFileConventions.IsCountableSourceFile(path));
        }
        finally
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

}
